### ISSUE TITLE
Add support for boolean variable type to better handle if statements.

### ISSUE THREAD

**Issue by josh-padnick** [gruntwork-io/boilerplate#5] opened 2016-08-09 16:35 UTC
In the README, the following files are suggested as examples:

**boilerplate.yml**
```yaml
variables:
  ...
  - name: ShowLogo
    prompt: Should the webiste show the logo?
    default: true
```

**index.html**
```html
<html>
   ...
  <body>
    ...
    {{if .ShowLogo}}<img src="logo.png">{{end}}
  </body>
</html>
```

But as written, this example will always render the `<img>` tag because boilerplate doesn't yet support any variable type other than string. In this case, a boolean type would allow this to work.

As a string, the only way to get the `if` statement to be false is for `.ShowLogo` to be empty, which requires that no default value be defined.

**Comment by brikis98** [comment] 2016-09-08 23:48
I'm going to close this as a duplicate of #9. 

FWIW, the current work around for booleans is to compare the variable to the string "true". E.g.:

```
{{ if eq .ShowLogo "true" }} 
(do something)
{{ end }}
```

**Closed by brikis98** 2016-09-08 23:48 UTC
Labels: P: Medium, T: Enhancement
